# Generated by Django 3.2.13 on 2022-06-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='change',
            name='action',
            field=models.IntegerField(choices=[(0, '---'), (1, 'Create'), (2, 'Delete'), (3, 'Update')], default=0, help_text='Change action.', verbose_name='Change action'),
        ),
    ]
