# Generated by Django 3.2.13 on 2022-06-24 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0002_change_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='change',
            name='active',
        ),
        migrations.RemoveField(
            model_name='change',
            name='description',
        ),
        migrations.RemoveField(
            model_name='change',
            name='name',
        ),
        migrations.RemoveField(
            model_name='change',
            name='root',
        ),
    ]
