# Generated by Django 3.2.13 on 2022-06-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0003_auto_20220624_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='before',
            field=models.JSONField(blank=True, help_text='CLI command name.', max_length=64, null=True, verbose_name='Command name'),
        ),
    ]
