# Generated by Django 3.2.13 on 2022-06-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0004_alter_change_before'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='change',
            name='deleted',
        ),
        migrations.AlterField(
            model_name='change',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Change create date.', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='change',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Change last update date.', verbose_name='Updated'),
        ),
    ]
