# Generated by Django 3.2.13 on 2022-05-23 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='color',
            field=models.ForeignKey(blank=True, help_text='Corelated color.', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.color', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='device',
            name='color',
            field=models.ForeignKey(blank=True, help_text='Corelated color.', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.color', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(blank=True, help_text='Type of network device system.', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.devicetype', verbose_name='Device type'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='ico',
            field=models.IntegerField(choices=[(0, 'static/ico/model/devices/switch.svg'), (1, 'static/ico/model/devices/border_router.svg'), (2, 'static/ico/model/devices/chassis.svg'), (3, 'static/ico/model/devices/console.svg'), (4, 'static/ico/model/devices/firewall.svg'), (5, 'static/ico/model/devices/router.svg'), (6, 'static/ico/model/devices/router_firewall.svg'), (7, 'static/ico/model/devices/router_wifi_1.svg'), (8, 'static/ico/model/devices/router_wifi_2.svg'), (9, 'static/ico/model/devices/stack.svg'), (10, 'static/ico/model/devices/stack_firewall_1.svg'), (11, 'static/ico/model/devices/stack_firewall_2.svg'), (12, 'static/ico/model/devices/switch.svg'), (13, 'static/ico/model/devices/wifi-connection.svg'), (14, 'static/ico/model/devices/wireless-router.svg')], default=0, help_text='Device type graphical representation.', verbose_name='Device type icon'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='color',
            field=models.ForeignKey(blank=True, help_text='Corelated color.', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.color', verbose_name='Color'),
        ),
    ]
