# Generated by Django 3.2.13 on 2022-05-25 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicecolor',
            options={'verbose_name': 'Device color', 'verbose_name_plural': 'Device colors'},
        ),
        migrations.AlterModelOptions(
            name='devicecredential',
            options={'verbose_name': 'Device credential', 'verbose_name_plural': 'Device credentials'},
        ),
        migrations.AlterModelOptions(
            name='devicegroup',
            options={'verbose_name': 'Device group', 'verbose_name_plural': 'Device groups'},
        ),
        migrations.AlterModelOptions(
            name='devicetypetemplate',
            options={'verbose_name': 'Device type template', 'verbose_name_plural': 'Device type templates'},
        ),
        migrations.AlterModelOptions(
            name='policytask',
            options={'verbose_name': 'Policy task', 'verbose_name_plural': 'Policy tasks'},
        ),
        migrations.AlterModelOptions(
            name='policytemplate',
            options={'verbose_name': 'Policy template', 'verbose_name_plural': 'Policy templates'},
        ),
        migrations.RenameField(
            model_name='devicetypetemplate',
            old_name='template',
            new_name='command',
        ),
        migrations.RemoveField(
            model_name='devicetypetemplate',
            name='regex_expression',
        ),
        migrations.AddField(
            model_name='devicetype',
            name='device_type_templates',
            field=models.ManyToManyField(blank=True, help_text='All devices type templates.', to='inventory.DeviceTypeTemplate', verbose_name='Device type template/s'),
        ),
        migrations.AlterField(
            model_name='devicegroup',
            name='color',
            field=models.ForeignKey(blank=True, help_text='Correlated color.', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.devicecolor', verbose_name='Color'),
        ),
    ]
