# Generated by Django 3.2.13 on 2022-05-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='color',
            field=models.IntegerField(choices=[(0, 'static/ico/model/colors/switch.svg'), (1, 'static/ico/model/colors/border_router.svg'), (2, 'static/ico/model/colors/chassis.svg'), (3, 'static/ico/model/colors/console.svg'), (4, 'static/ico/model/colors/firewall.svg'), (5, 'static/ico/model/colors/router.svg'), (6, 'static/ico/model/colors/router_firewall.svg'), (7, 'static/ico/model/colors/router_wifi_1.svg'), (8, 'static/ico/model/colors/router_wifi_2.svg'), (9, 'static/ico/model/colors/stack.svg'), (10, 'static/ico/model/colors/stack_firewall_1.svg'), (11, 'static/ico/model/colors/stack_firewall_2.svg'), (12, 'static/ico/model/colors/stack_firewall_2.svg'), (13, 'static/ico/model/colors/stack_firewall_2.svg')], default=0, help_text='Color graphic representation.', verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='device',
            name='color',
            field=models.IntegerField(choices=[(0, 'static/ico/model/colors/switch.svg'), (1, 'static/ico/model/colors/border_router.svg'), (2, 'static/ico/model/colors/chassis.svg'), (3, 'static/ico/model/colors/console.svg'), (4, 'static/ico/model/colors/firewall.svg'), (5, 'static/ico/model/colors/router.svg'), (6, 'static/ico/model/colors/router_firewall.svg'), (7, 'static/ico/model/colors/router_wifi_1.svg'), (8, 'static/ico/model/colors/router_wifi_2.svg'), (9, 'static/ico/model/colors/stack.svg'), (10, 'static/ico/model/colors/stack_firewall_1.svg'), (11, 'static/ico/model/colors/stack_firewall_2.svg'), (12, 'static/ico/model/colors/stack_firewall_2.svg'), (13, 'static/ico/model/colors/stack_firewall_2.svg')], default=0, help_text='Color graphic representation.', verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='folder',
            name='color',
            field=models.IntegerField(choices=[(0, 'static/ico/model/colors/switch.svg'), (1, 'static/ico/model/colors/border_router.svg'), (2, 'static/ico/model/colors/chassis.svg'), (3, 'static/ico/model/colors/console.svg'), (4, 'static/ico/model/colors/firewall.svg'), (5, 'static/ico/model/colors/router.svg'), (6, 'static/ico/model/colors/router_firewall.svg'), (7, 'static/ico/model/colors/router_wifi_1.svg'), (8, 'static/ico/model/colors/router_wifi_2.svg'), (9, 'static/ico/model/colors/stack.svg'), (10, 'static/ico/model/colors/stack_firewall_1.svg'), (11, 'static/ico/model/colors/stack_firewall_2.svg'), (12, 'static/ico/model/colors/stack_firewall_2.svg'), (13, 'static/ico/model/colors/stack_firewall_2.svg')], default=0, help_text='Color graphic representation.', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='ico',
            field=models.IntegerField(choices=[(0, 'static/ico/model/users/manager-1.svg'), (1, 'static/ico/model/users/afro-hair-dark.svg'), (2, 'static/ico/model/users/afro-hair.svg'), (3, 'static/ico/model/users/bald.svg'), (4, 'static/ico/model/users/beard.svg'), (5, 'static/ico/model/users/business-man.svg'), (6, 'static/ico/model/users/business-woman.svg'), (7, 'static/ico/model/users/businessman-2.svg'), (8, 'static/ico/model/users/businessman.svg'), (9, 'static/ico/model/users/goth.svg'), (10, 'static/ico/model/users/grandmother.svg'), (11, 'static/ico/model/users/grandpa.svg'), (12, 'static/ico/model/users/hair-bun.svg'), (13, 'static/ico/model/users/japanese.svg'), (14, 'static/ico/model/users/long-haired.svg'), (15, 'static/ico/model/users/man-1.svg'), (16, 'static/ico/model/users/man-2.svg'), (17, 'static/ico/model/users/man.svg'), (18, 'static/ico/model/users/manager-2.svg'), (19, 'static/ico/model/users/nerd.svg'), (20, 'static/ico/model/users/nurse-2.svg'), (21, 'static/ico/model/users/nurse.svg'), (22, 'static/ico/model/users/punk-2.svg'), (23, 'static/ico/model/users/punk.svg'), (24, 'static/ico/model/users/short-hair.svg'), (25, 'static/ico/model/users/skater-2.svg'), (26, 'static/ico/model/users/skater.svg'), (27, 'static/ico/model/users/turtleneck-2.svg'), (28, 'static/ico/model/users/turtleneck.svg'), (29, 'static/ico/model/users/woman-2.svg'), (30, 'static/ico/model/users/woman-3.svg'), (31, 'static/ico/model/users/woman-4.svg'), (32, 'static/ico/model/users/woman.svg')], default=0, help_text='Credential graphical representation.', verbose_name='Credential icon'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ico',
            field=models.IntegerField(choices=[(0, 'static/ico/model/devices/switch.svg'), (1, 'static/ico/model/devices/border_router.svg'), (2, 'static/ico/model/devices/chassis.svg'), (3, 'static/ico/model/devices/console.svg'), (4, 'static/ico/model/devices/firewall.svg'), (5, 'static/ico/model/devices/router.svg'), (6, 'static/ico/model/devices/router_firewall.svg'), (7, 'static/ico/model/devices/router_wifi_1.svg'), (8, 'static/ico/model/devices/router_wifi_2.svg'), (9, 'static/ico/model/devices/stack.svg'), (10, 'static/ico/model/devices/stack_firewall_1.svg'), (11, 'static/ico/model/devices/stack_firewall_2.svg'), (12, 'static/ico/model/devices/switch.svg'), (13, 'static/ico/model/devices/wifi-connection.svg'), (14, 'static/ico/model/devices/wireless-router.svg')], default=0, help_text='Network device graphic representation.', verbose_name='Device icon'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='ico',
            field=models.IntegerField(choices=[(0, 'static/ico/model/folders/folder-1.svg'), (1, 'static/ico/model/folders/folder-2.svg'), (2, 'static/ico/model/folders/folder-3.svg'), (3, 'static/ico/model/folders/folder-4.svg'), (4, 'static/ico/model/folders/folder-5.svg'), (5, 'static/ico/model/folders/folder-6.svg'), (6, 'static/ico/model/folders/folder-7.svg'), (7, 'static/ico/model/folders/folder-8.svg'), (8, 'static/ico/model/folders/folder-9.svg'), (9, 'static/ico/model/folders/folder-10.svg'), (10, 'static/ico/model/folders/folder-11.svg'), (11, 'static/ico/model/folders/folder-12.svg'), (12, 'static/ico/model/folders/folder-13.svg'), (13, 'static/ico/model/folders/folder-14.svg'), (14, 'static/ico/model/folders/folder-15.svg'), (15, 'static/ico/model/folders/folder-16.svg'), (16, 'static/ico/model/folders/folder-17.svg'), (17, 'static/ico/model/folders/folder-18.svg'), (18, 'static/ico/model/folders/folder-18.svg')], default=0, help_text='Folder graphic representation.', verbose_name='Folder icon'),
        ),
    ]
