# Generated by Django 3.2.13 on 2022-05-18 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
        ('inventory', '0002_auto_20220516_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='color',
            field=models.IntegerField(choices=[(0, 'static/ico/model/colors/color0.svg'), (1, 'static/ico/model/colors/color1.svg'), (2, 'static/ico/model/colors/color2.svg'), (3, 'static/ico/model/colors/color3.svg'), (4, 'static/ico/model/colors/color4.svg'), (5, 'static/ico/model/colors/color5.svg'), (6, 'static/ico/model/colors/color6.svg'), (7, 'static/ico/model/colors/color7.svg'), (8, 'static/ico/model/colors/color8.svg'), (9, 'static/ico/model/colors/color9.svg'), (10, 'static/ico/model/colors/color10.svg'), (11, 'static/ico/model/colors/color11.svg'), (12, 'static/ico/model/colors/color12.svg'), (13, 'static/ico/model/colors/color13.svg')], default=0, help_text='Color graphic representation.', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='device',
            name='color',
            field=models.IntegerField(choices=[(0, 'static/ico/model/colors/color0.svg'), (1, 'static/ico/model/colors/color1.svg'), (2, 'static/ico/model/colors/color2.svg'), (3, 'static/ico/model/colors/color3.svg'), (4, 'static/ico/model/colors/color4.svg'), (5, 'static/ico/model/colors/color5.svg'), (6, 'static/ico/model/colors/color6.svg'), (7, 'static/ico/model/colors/color7.svg'), (8, 'static/ico/model/colors/color8.svg'), (9, 'static/ico/model/colors/color9.svg'), (10, 'static/ico/model/colors/color10.svg'), (11, 'static/ico/model/colors/color11.svg'), (12, 'static/ico/model/colors/color12.svg'), (13, 'static/ico/model/colors/color13.svg')], default=0, help_text='Color graphic representation.', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='color',
            field=models.IntegerField(choices=[(0, 'static/ico/model/colors/color0.svg'), (1, 'static/ico/model/colors/color1.svg'), (2, 'static/ico/model/colors/color2.svg'), (3, 'static/ico/model/colors/color3.svg'), (4, 'static/ico/model/colors/color4.svg'), (5, 'static/ico/model/colors/color5.svg'), (6, 'static/ico/model/colors/color6.svg'), (7, 'static/ico/model/colors/color7.svg'), (8, 'static/ico/model/colors/color8.svg'), (9, 'static/ico/model/colors/color9.svg'), (10, 'static/ico/model/colors/color10.svg'), (11, 'static/ico/model/colors/color11.svg'), (12, 'static/ico/model/colors/color12.svg'), (13, 'static/ico/model/colors/color13.svg')], default=0, help_text='Color graphic representation.', verbose_name='Color'),
        ),
        migrations.CreateModel(
            name='DeviceCollectedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Model create date.', verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Model last update date.', verbose_name='Updated')),
                ('result_status', models.BooleanField(default=False, help_text='A positive result means that command updates was collected.', verbose_name='Result status')),
                ('command_name', models.CharField(help_text='CLI command name.', max_length=64, verbose_name='Command name')),
                ('command_raw_data', models.TextField(blank=True, help_text='CLI command raw data output.', null=True, verbose_name='Command raw data')),
                ('command_processed_data', models.JSONField(blank=True, help_text='CLI command FSM proccess data.', null=True, verbose_name='Command processed data')),
                ('update', models.ForeignKey(help_text='Corelated update model.', on_delete=django.db.models.deletion.CASCADE, to='automation.deviceupdate', verbose_name='Update model')),
            ],
            options={
                'verbose_name': 'Device colected data',
                'verbose_name_plural': 'Device colected data',
            },
        ),
    ]
