# Generated by Django 3.2.13 on 2022-05-26 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20220525_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicetype',
            name='device_type_templates',
        ),
        migrations.AddField(
            model_name='devicetypetemplate',
            name='device_type',
            field=models.ForeignKey(blank=True, help_text='Xxx.', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.devicetype', verbose_name='Device type'),
        ),
    ]
