# Generated by Django 3.2.13 on 2022-05-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20220518_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecollecteddata',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
