# Generated by Django 3.2.13 on 2022-05-28 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20220526_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='color',
            field=models.ForeignKey(blank=True, help_text='Correlated color.', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.devicecolor', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='napalm_name',
            field=models.CharField(default='Test', help_text='Napalm name.', max_length=32, verbose_name='Napalm name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='netmiko_name',
            field=models.CharField(default='Test', help_text='Netmiko name.', max_length=32, verbose_name='Netmiko name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devicetypetemplate',
            name='command',
            field=models.TextField(default='Test', help_text='CLI command/s template.', verbose_name='CLI template'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devicetypetemplate',
            name='sfm_expression',
            field=models.TextField(default='Test', help_text='SFM expression used to check if CLI command/s output is correct.', verbose_name='SFM expression'),
            preserve_default=False,
        ),
    ]
