# Generated by Django 3.2.13 on 2022-05-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_devicecollecteddata_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicecollecteddata',
            options={'verbose_name': 'Device collected data', 'verbose_name_plural': 'Device collected data'},
        ),
        migrations.AddField(
            model_name='devicecollecteddata',
            name='processed_data_status',
            field=models.BooleanField(default=False, help_text='A positive result means that command updates was collected.', verbose_name='Result status'),
        ),
        migrations.AddField(
            model_name='devicecollecteddata',
            name='raw_data_status',
            field=models.BooleanField(default=False, help_text='A positive result means that command updates was collected.', verbose_name='Result status'),
        ),
    ]
