# Generated by Django 3.2.13 on 2022-05-29 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_devicetypetemplate_command'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicetype',
            name='device_type_templates',
        ),
        migrations.AddField(
            model_name='devicetypetemplate',
            name='device_type',
            field=models.ForeignKey(default=1, help_text='Type of network device system.', on_delete=django.db.models.deletion.CASCADE, to='inventory.devicetype', verbose_name='Device type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devicecollecteddata',
            name='command_processed_data',
            field=models.JSONField(blank=True, help_text='CLI command FSM process data.', null=True, verbose_name='Command processed data'),
        ),
        migrations.AlterField(
            model_name='devicecollecteddata',
            name='device_update',
            field=models.ForeignKey(help_text='Correlated update model.', on_delete=django.db.models.deletion.CASCADE, to='inventory.deviceupdate', verbose_name='Update model'),
        ),
        migrations.AlterField(
            model_name='devicetypetemplate',
            name='command',
            field=models.CharField(help_text='CLI command that will be executed on network device.', max_length=32, unique=True, verbose_name='CLI command'),
        ),
    ]
