# Generated by Django 3.2.13 on 2022-05-29 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20220529_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicetypetemplate',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='devicetypetemplate',
            unique_together={('command', 'device_type')},
        ),
    ]
