# Generated by Django 3.2.13 on 2022-05-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20220529_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetype',
            name='napalm_name',
            field=models.CharField(help_text='Napalm name.', max_length=32, unique=True, verbose_name='Napalm name'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='netmiko_name',
            field=models.CharField(help_text='Netmiko name.', max_length=32, unique=True, verbose_name='Netmiko name'),
        ),
    ]
