# Generated by Django 3.2.13 on 2022-06-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20220529_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetypetemplate',
            name='template_type',
            field=models.IntegerField(choices=[(0, 'Undefined'), (1, 'Command template'), (2, 'API template')], default=0, help_text='Device template type.', verbose_name='Template type'),
        ),
        migrations.AddField(
            model_name='devicetypetemplate',
            name='url',
            field=models.TextField(blank=True, help_text='URL required to collect API response from device.', null=True, verbose_name='API URL'),
        ),
        migrations.AlterField(
            model_name='devicetypetemplate',
            name='command',
            field=models.CharField(blank=True, help_text='CLI command that will be executed on network device.', max_length=32, null=True, verbose_name='CLI command'),
        ),
        migrations.AlterField(
            model_name='devicetypetemplate',
            name='sfm_expression',
            field=models.TextField(blank=True, help_text='SFM expression used to check if CLI command/s output is correct.', null=True, verbose_name='SFM expression'),
        ),
        migrations.AlterField(
            model_name='deviceupdate',
            name='status',
            field=models.IntegerField(choices=[(0, 'Initiation'), (1, 'Successfully collected data'), (2, 'Data collection failed')], default=0, help_text='Device update status.', verbose_name='Update status'),
        ),
    ]
