# Generated by Django 3.2.13 on 2022-06-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20220618_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetypetemplate',
            name='url',
            field=models.CharField(blank=True, help_text='URL required to collect API response from device.', max_length=256, null=True, verbose_name='API URL'),
        ),
    ]
