# Generated by Django 3.2.13 on 2022-06-18 20:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20220618_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetype',
            name='netmiko_name',
            field=models.CharField(default=django.utils.timezone.now, help_text='Netmiko name.', max_length=32, unique=True, verbose_name='Netmiko name'),
            preserve_default=False,
        ),
    ]
