# Generated by Django 3.2.13 on 2022-05-18 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_auto_20220516_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Model create date.', verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Model last update date.', verbose_name='Updated')),
                ('status', models.IntegerField(choices=[(0, 'Initiation'), (1, 'Collecting data'), (2, 'Saved data')], default=0, help_text='Device update status.', verbose_name='Update status')),
                ('result_status', models.BooleanField(default=False, help_text='A positive result means that all commands updates was collected.', verbose_name='Result status')),
                ('device', models.ForeignKey(help_text='The network device affected by the update.', on_delete=django.db.models.deletion.CASCADE, to='inventory.device', verbose_name='Device')),
            ],
            options={
                'verbose_name': 'Device update',
                'verbose_name_plural': 'Device updates',
            },
        ),
    ]
