# Generated by Django 3.2.13 on 2022-05-23 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('automation', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='devices',
            field=models.ManyToManyField(blank=True, help_text='Xxx.', to='inventory.Device', verbose_name='Corelated device/s'),
        ),
        migrations.AddField(
            model_name='policy',
            name='folders',
            field=models.ManyToManyField(blank=True, help_text='Xxx.', to='inventory.Folder', verbose_name='Corelated folder/s'),
        ),
        migrations.AddField(
            model_name='policy',
            name='scheduler',
            field=models.ForeignKey(blank=True, help_text='Task scheduler.', null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.intervalschedule', verbose_name='Scheduler'),
        ),
        migrations.AddField(
            model_name='policy',
            name='templates',
            field=models.ManyToManyField(blank=True, help_text='Xxx.', to='automation.Template', verbose_name='Corelated template/s'),
        ),
        migrations.AddField(
            model_name='deviceupdate',
            name='device',
            field=models.ForeignKey(help_text='The network device affected by the update.', on_delete=django.db.models.deletion.CASCADE, to='inventory.device', verbose_name='Device'),
        ),
    ]
