# Generated by Django 3.2.13 on 2022-05-18 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_devicecollecteddata_deleted'),
        ('automation', '0003_auto_20220518_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policyrunner',
            options={'verbose_name': 'Policy runner', 'verbose_name_plural': 'Policy runner'},
        ),
        migrations.AlterField(
            model_name='policy',
            name='devices',
            field=models.ManyToManyField(blank=True, help_text='Xxx.', null=True, to='inventory.Device', verbose_name='Corelated device/s'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='folders',
            field=models.ManyToManyField(blank=True, help_text='Xxx.', null=True, to='inventory.Folder', verbose_name='Corelated folder/s'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='templates',
            field=models.ManyToManyField(blank=True, help_text='Xxx.', null=True, to='automation.Template', verbose_name='Corelated template/s'),
        ),
        migrations.AlterField(
            model_name='policyrunner',
            name='policy',
            field=models.ForeignKey(help_text='Corelated policy.', on_delete=django.db.models.deletion.CASCADE, to='automation.policy', verbose_name='Policy'),
        ),
        migrations.AlterField(
            model_name='policyrunner',
            name='status',
            field=models.IntegerField(choices=[(0, 'Initiation'), (1, 'Collecting data'), (2, 'Saved data')], default=0, help_text='Policy runner status.', verbose_name='Update status'),
        ),
        migrations.AlterField(
            model_name='template',
            name='regex_expression',
            field=models.TextField(blank=True, help_text='Regex expression used to check if CLI command/s output is correct.', null=True, verbose_name='Regex expression'),
        ),
        migrations.AlterField(
            model_name='template',
            name='sfm_expression',
            field=models.TextField(blank=True, help_text='SFM expression used to check if CLI command/s output is correct.', null=True, verbose_name='SFM expression'),
        ),
        migrations.AlterField(
            model_name='template',
            name='template',
            field=models.TextField(blank=True, help_text='CLI command/s template.', null=True, verbose_name='CLI template'),
        ),
    ]
