# Generated by Django 3.2.13 on 2022-05-29 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogDetails',
        ),
    ]
